# pylint: disable-all
# Generated by Django 5.1.2 on 2025-01-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='request_retrieved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='request_supplied',
            field=models.BooleanField(default=False),
        ),
    ]
