# pylint: disable-all
# Generated by Django 5.1.2 on 2025-01-13 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_request_request_retrieved_request_request_supplied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='supplier',
        ),
    ]
